server:
  port: 8762

eureka:
  cloud:
    server:
      url: localhost
      post: 8761
  client:
    service-url:
      default-zone: http://${eureka.cloud.server.url}:${eureka.cloud.server.post}/eureka/

spring:
  application:
    name: service-hi
